version: '3.8'

services:
  melodia-chart:
    build: .
    container_name: melodia-chart
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./melodia.db:/app/melodia.db
    environment:
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
